### ISSUE TITLE
An example to use rust-peg to return which match parts?

### ISSUE THREAD

**Issue by ivanceras** [kevinmehall/rust-peg#114]
```rust
#![feature(plugin)]
#![plugin(peg_syntax_ext)]
use arithmetic::expression;

peg! arithmetic(r#"
#[pub]
expression -> i64
	= sum
sum -> i64
	= l:product "+" r:product { l+r }
	/ product
product -> i64
	= l:atom "*" r:atom { l*r }
	/ atom
atom -> i64
	= number
	/ "(" v:sum ")" { v }
number -> i64
	= [0-9]+ { match_str.parse().unwrap() }
"#);

#[test]
fn main() {
	assert_eq!(expression("1+1"), Ok(2));
	assert_eq!(expression("5*5"), Ok(25));
	assert_eq!(expression("222+3333"), Ok(3555));
	assert_eq!(expression("2+3*4"), Ok(14));
	assert_eq!(expression("(2+2)*3"), Ok(12));
	assert!(expression("(22+)+1").is_err());
	assert!(expression("1++1").is_err());
	assert!(expression("3)+1").is_err());
}
```
I've seen most of the examples, which only returns Ok or Err.
I was expecting something like:

`expression("1+1")`  => `expression{ sum {l:product: '1', r:product: '1' }}`

Is this even the library I am looking for?

**Comment by kevinmehall** [comment]
The expressions in the curly braces could return a structure instead of performing the arithmetic right there. I've added [a version of the arithmetic example that shows how to do this](https://github.com/kevinmehall/rust-peg/blob/master/tests/test_arithmetic_ast.rs).

You can also look at more complicated users of rust-peg, like [signalspec's parser](https://github.com/signalspec/signalspec/blob/master/src/signalspec.rustpeg) which builds [a more complex AST](https://github.com/signalspec/signalspec/blob/master/src/ast.rs).

**Comment by ivanceras** [comment]
@kevinmehall  Thanks, I've just built what I want using your awesome library https://github.com/ivanceras/inquerest
