### ISSUE TITLE
[Question] How can I make expanded module public?

### ISSUE THREAD

**Issue by y-ich** [kevinmehall/rust-peg#115]
Hi.

Writing peg_file! in main.rs works fine, but when I put peg_file! in my module, the expanded submodule is private and can not access it in main.rs.

How can I make it public?

**Comment by untitaker** [comment]
IMO you're supposed to write your own public API. If you exposed the module directly it would be like leaking the implementation detail that you're using rust-peg.

Consider this: What if rust-peg changes the API it generates? If you export the module directly, user code would fail to compile instead of your own crate.

On 12 November 2015 04:37:17 CET, y-ich <notifications@github.com> wrote:
>Hi.
>
>Writing peg_file! in main.rs works fine, but when I put peg_file! in my
>module, the expanded submodule is private and can not access it in
>main.rs.
>
>How can I make it public?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/kevinmehall/rust-peg/issues/115

-- 
Sent from my phone. Please excuse my brevity.

**Comment by kevinmehall** [comment]
Agreed with @untitaker.
