### ISSUE TITLE
ParseError that should not be possible

### ISSUE THREAD

**Issue by skylerberg** [kevinmehall/rust-peg#123]
I have been running into some weird parse errors. To check my sanity I added a base case to my root function that should catch everything. That way no parse errors should be possible. However, I still get the errors. The base case along with the rest of the code I am working with is at: https://github.com/skylerberg/ion/blob/parser/src/peg.rs#L30.

The errors I am getting in my tests are:
```
---- peg::tests::indentation_on_multiple_lines stdout ----
	thread 'peg::tests::indentation_on_multiple_lines' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError { line: 2, column: 3, offset: 7, expected: {"[#]", "[ \t]", "[\r\n]"} }', ../src/libcore/result.rs:688

---- peg::tests::leading_whitespace stdout ----
	thread 'peg::tests::leading_whitespace' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError { line: 1, column: 6, offset: 5, expected: {"[\r\n]", "[;]", "[ \t]", "[#]"} }', ../src/libcore/result.rs:688
```

**Comment by kevinmehall** [comment]
This happens because your  `job_list` rule accepts either entirely `job`s or entirely `blank_line`s because the ordered choice `/` is outside of the repetition.

`indentation_on_multiple_lines` matches `echo` via the first `job` arm, then can't match the leading whitespace of the next line to make another iteration of the repetition, so the entire toplevel rule accepts the prefix `echo`, and fails because the rest of the string remains unmatched.

`leading_whitespace` matches the prefix "    \t" via the `blank_line` arm, and then can't extend that repetition with another `blank_line`.

PEGs don't backtrack and try to match another way when an ordered-choice arm successfully matches. That is, `"a" / "abc"` will fail on input "abc" because the first arm of the ordered choice matches, and nothing follows to match the remaining "bc". The issue you're seeing is that one of the first two arms of `job_list` matches one iteration at the beginning of the input string, so it never even tries the `.*` arm, and fails because it did not reach the end of the input string. The `**` in the second arm will even accept the empty string by repeating zero times, so the `.*` arm is unreachable.

The bug in `rust-peg` is that it's not listing `EOF` in the set of expected tokens, since matching the toplevel rule without covering the entire input is why it's giving up and reporting the error. It would also catch errors like this if it could report unreachable expressions, though this might be hard in the general case.

I think you want something like:
```
job_list -> Vec<Job>
    = jobs:(whitespace* job:job job_ending {job})* blank_line? {jobs}
```

If you run `cargo test --features peg/trace`, it will dump a log of when the parser enters and exits each rule.

**Comment by skylerberg** [comment]
Thanks so much for the help! The issue was that I was expecting backtracking. So as soon as any of it matches, then I will never see another arm. That was the bulk of my confusion today.

I managed to hack something together that works, but your answer will help me a lot when I go to extend and clean it.

When you say the bug is not listing `EOF` do you mean not having a way to match EOF?

**Comment by kevinmehall** [comment]
When you put `#[pub] job_list`, `rust-peg` generates a wrapper function that behaves as if it were matching `job_list EOF` to check that the `job_list` rule matches the entire input string. That wrapper currently just falls through and reports the previous errors encountered in that case, but it should mention "EOF" in the error set, because removing characters at the end of the input string would make it match. (If you want to explicitly match  EOF within a PEG, you can write `EOF = !.`, because `.` only fails to match when there isn't another character)
