### ISSUE TITLE
Odd interaction between / and overlapping subrules

### ISSUE THREAD

**Issue by kazimuth** [kevinmehall/rust-peg#151]
It's entirely possible that I'm doing something wrong here, but:

When I run the tests in [this gist](https://gist.github.com/kazimuth/8f98c1d3c371961dfe2f5c1ac54649f7), they fail with the message:
```rust
thread 'tests::test_parse_f64s' panicked at 'assertion failed: `(left == right)` (left: `Ok(F64(37330000000000000))`, right: `Err(ParseError { line: 1, column: 3, offset: 2, expected: {"[a-fA-F0-9]"} })`)', src/lib.rs:34
```

The failing test is:
```
assert_eq!(Ok(F64(37.33e15)),    number::numeric_constant("37.33e15"));
```

But the others pass, which is the perplexing part.

What I would expected to happen is either it fails with a parse error with `expected: {"numeric constant"}`, or succeeds.

I'll rewrite it so that it just uses a single rule to parse all numbers (it's a fairly janky thing to be doing anyway... I might just use `num`), but this could indicate an error in `peg`, so I'm reporting it anyway.

**Comment by kevinmehall** [comment]
That's how PEG parsers behave. `/` is ordered choice -- it tries the first expression, and if it succeeds, it's done, otherwise it tries the alternative. There is no backtracking into the other choices of the `/` on a failure later in the string. In your test, the `u64literal` rule matches, and there's no rule after `u64literal` handle the ".".

Common strategies for dealing with this include:
  * Order the choices from most specific to least specific if they can be strictly ordered.
  * Use lookahead to explicitly exclude possible continuations that should be handled by another rule (e.g. `[a-fA-F0-9]+ !"."`).
  * Combine overlapping choices into a single rule with optional parts (`?`) and handle the differences in the action code.
