### ISSUE TITLE
Why does {? ... } error type have to be &str?

### ISSUE THREAD

**Issue by jiri** [kevinmehall/rust-peg#188]
I have a rule for parsing `i16`, that looks like this:

```
int -> i16 = s:$([+-]?[0-9]+) {? s.parse::<i16>() }
```

However, that won't compile, because the parse function returns a `Result<i16, ParseIntError>` and if I understand correctly rust-peg expects the error type to be `&str`. Mapping `|x| x.description()` doesn't work either, because the lifetime of `x` isn't long enough to return a string slice.

Is there a way to solve this? Could rust-peg maybe accept any type that implements `Display` and/or `Debug`?

**Comment by kevinmehall** [comment]
The `{? ...}` construct works by adding the `Err()` return value to the set of expected matches at that position. For instance, `{? Err("foo") } / "bar"` may return the error `Expected foo or bar`. So here, you could use `.map_err(|_| "16-bit hex constant")` or something to add that message to the error set on failure.

If it were able to return a `ParseIntError` or `Display` what would you want it to do with the error? Anything that allocates, such as converting to a `String` would be a performance issue, because most of the time the error is not even used when another alternative matches. Do you have a use case for an error that must be a dynamically-generated string?

`&'static str` is really the lowest common denominator that is able to cover most use cases. 
I'd like to redesign rust-peg's error handling to be more flexible, but the errors will probably still have to all be a common type. You could perhaps choose `String` or `Box<Display>` and take the performance hit if you really wanted to, but I envision this mostly being used with a custom error enum.

**Comment by jiri** [comment]
I see, that makes sense. Thanks :)
