### ISSUE TITLE
Add support for incremental parsing

### ISSUE THREAD

**Issue by sandeep-datta** [kevinmehall/rust-peg#192]
It'd be great if we could use the generated parser to parse incomplete input strings incrementally. This may be useful (for example) in parsing data received in bits and pieces from a remote server or as multi-line input from a command shell.

I think we can start by

Redefining ...
`pub type ParseResult<T> = Result<T, ParseError>;`
as ...
`pub type ParseResult<T> = Result<T, (ParseError, ParseState)>;`

and the generated public interface ...
`pub fn my_expression<'input>(__input: &'input str) -> ParseResult<Number> {...`
as ...
`pub fn my_expression<'input>(__input: &'input str, state: ParseState) -> ParseResult<Number> {...`

The struct `ParseState` can be exported as an opaque data type so that it cannot be modified by the end user.

Here is how you'll use this arrangement (glossing over some implementation details) ...
1. Read a (potentially) partial string from some source and append it to an empty input buffer.
2. Pass the input buffer to the parser's public interface (`my_expression` in this example). If the parse is successful make use of the result and goto step 1. If it is not then return the tuple `(ParseError, ParseState)`.
3. Read another piece of (potentially) partial string from the source and append it to the input buffer. Now pass this buffer again to `my_expression` but this time with the ParseState obtained in step 2. This will _(when this feature is implemented)_ cause the parser to resume parsing from where it left off in step 2 without reparsing everything from start.
...

I hope you see the pattern now.

**Comment by kevinmehall** [comment]
Unfortunately, the `ParseState` is just the caches and error reporting information, while the enclosing rules and their state is just stored on the Rust call stack. So it would have to be completely redesigned to store all state in a structure to be able to resume, at a performance and complexity penalty.

Additionally, since PEG allows infinite backtracking, you'd have to buffer the entire input anyway, so I'm not sure what benefit this would have over buffering the input externally and parsing all at once.

**Comment by sandeep-datta** [comment]
> Additionally, since PEG allows infinite backtracking, you'd have to buffer the entire input anyway, so I'm not sure what benefit this would have over buffering the input externally and parsing all at once.

I did not want the parser to "buffer the input externally and parse all at once" but instead incrementally return partial match information as new input arrived. It is possible at any given point you would not have sufficient information to match a rule completely but in that case you'd wait for more input (or EOF) to arrive (as long as parts of the rule kept matching the input). If the current rule failed you'd backtrack and try again (as you'd do in the normal case).

> you'd have to buffer the entire input anyway
I have already indicated in the original request that this is not a problem.

Two example use cases: 
1. Imagine a command interpreter which needs to show a secondary prompt when it is expecting more input from the user. How do you know if further input is pending? The parser could furnish this information if it was designed to do so. Also by saving the intermediate parse state you could continue the parse operation from where you left off previously instead of starting it from position zero again.

2. A widget layout engine which uses the information obtained so far (as a DSL describing UI like say HTML) to show a partial rendering of the GUI until complete information arrives over the network. In most cases the partial rendering will be close to the final rendering and to the end user the GUI will appear to be constructed incrementally.

> Unfortunately, the ParseState is just the caches and error reporting information, while the enclosing rules and their state is just stored on the Rust call stack. So it would have to be completely redesigned to store all state in a structure to be able to resume, at a performance and complexity penalty.

Fair enough!

**Comment by kevinmehall** [comment]
If you're envisioning an expression like `command*` returning individual commands incrementally, that would require some significant analysis of the grammar or "cut" annotation to ensure that backtracking can't change the result. Normally, PEG has to fully match the top-level rule before committing to any result because it may backtrack and parse it differently.

> Imagine a command interpreter which needs to show a secondary prompt when it is expecting more input from the user. How do you know if further input is pending?

It can already do that. Parse the line as a single `command`, and if the reported error position is at the end of the buffer, that means it expected additional characters, so show a continuation prompt, concatenate the new line, and parse again. If it parses successfully, or fails with a different error, clear the buffer and show a new prompt. In this case you know where the command boundaries are, but if you didn't, the [ability to parse a prefix of the input](https://github.com/kevinmehall/rust-peg/issues/179#issuecomment-362929726) could parse a single complete command and return the remainder to keep in the buffer.

> A widget layout engine which uses the information obtained so far (as a DSL describing UI like say HTML) to show a partial rendering of the GUI until complete information arrives over the network.

In this case you're probably better off using a hand-written parser (like most HTML/XML parsers) or different parsing formalism. In the case of XML parsers, you often get a callback for each tag rather than returning a result.

**Comment by sandeep-datta** [comment]
Thanks!
