### ISSUE TITLE
Diifferentiating between decimal and hex

### ISSUE THREAD

**Issue by WarpspeedSCP** [kevinmehall/rust-peg#198]
I have a parser to differentiate between decimal and hex numbers, which looks like this-

The numbers that I parse must be within `0x00FFFFFF` and will be truncated if they are not.

```
pub dec -> i32 = val:$([-+]?[0-9]*<1, 8>) {
    i32::from_str_radix(val, 10).unwrap() & 0x00ffffffi32
}

pub hexbase -> i32 = val:$([-+]?[0-9]([0-9]/[a-fA-F])*<0, 6>) {
    i32::from_str_radix(val, 16).unwrap() & 0x00ffffffi32
}

pub hex -> i32 = h:hexbase g:&"h" {
    h
}

pub hex_lit -> i32 = e:"x\'" h:hexbase g:"\'" {
    h
}

pub num -> i32 = (dec / hex / hex_lit)
```

When I try using the `num` parser to parse a decimal number, or a hexadecimal literal (such as `x'23d'`), it works. But, when a hexadecimal number (such as `2dh`) is encountered, it fails at the decimal parser and returns, while I expect it to skip parsing the input as a decimal and try parsing it as a hexadecimal number instead.

Why does this occur, and what can I change to fix it?

**Comment by Mingun** [comment]
> Why does this occur, and what can I change to fix it?

You `dec` rule successfully match part `2` from input `2dh`. Because `dec` successfully matched, there is no backtracking and rule `num` also successfully matched. And then parser fails because not all input consumed.

Therefore rule `dec` is more specific then `hex` because any input that match `dec` also contains in `hex`.

So you need change order of the rules `dec` and `hex`. Also you `hex` rule does not consume `h` literal after `hex` and I think that is not that you expected, so I suppose you need also change `hex` rule.

So, after all changes, final grammar will be
```
pub dec -> i32 = val:$([-+]?[0-9]*<1, 8>) {
    i32::from_str_radix(val, 10).unwrap() & 0x00ffffffi32
}

pub hexbase -> i32 = val:$([-+]?[0-9]([0-9]/[a-fA-F])*<0, 6>) {
    i32::from_str_radix(val, 16).unwrap() & 0x00ffffffi32
}

pub hex -> i32 = h:hexbase "h" {//<<<<<< remove &
    h
}

pub hex_lit -> i32 = "x\'" h:hexbase "\'" {
    h
}

pub num -> i32 = (hex / hex_lit / dec)//<<<<<< change order
```

**Comment by WarpspeedSCP** [comment]
I see, that worked. thank you for the help!

**Comment by kevinmehall** [comment]
Ordered choice is inherently how PEG works. Most other parsing techniques wouldn't behave as you would want them to here either for what it's worth; they would report that the grammar is ambiguous.
