### ISSUE TITLE
Repeat expression that doesn't consume input should be a compile time error

### ISSUE THREAD

**Issue by hfiguiere** [kevinmehall/rust-peg#210]
I found this issue porting from 0.5.0 to 0.6.0.

When I run my parser test, it get stuck in an infinite loop (ie it never terminate).

This is the reduced test case:

```rust
extern crate peg;

peg::parser!{grammar p() for str {

pub rule string_literal() -> String
        = "\"" s:$((!['"'])*) "\"" { println!("literal {}", s); s.to_owned() }

}}

fn main() {

    let r = p::string_literal("\"literal\"");

    if let Ok(l) = r {
        println!("Parsed {}", l);
    } else {
        println!("Parse failed {:?}", r);
    }
}
```

Expected:
- either it doesn't compile because it's a syntax error (i.e. I'm doing the rule wrong with the update syntax)
- or it is a parse error

Instead it just get stuck when I `cargo run`.

**Comment by kevinmehall** [comment]
`(!['"'])*` matches nothing, repeatedly, as long as the next character is not a quote.

The `!X` operator is negative lookahead -- it matches the empty string if X fails to match, or fails to match if X matches at the current position. It looks like you're trying to use `(!['"'])*` as "any character besides `"`, presumably as a replacement for 0.5's `[^"]`. You actually want `(!['"'] [_])*` where the `[_]` consumes the character if it's not a quote.

0.6 adds compile-time checks for other patterns like left recursion that infinite loop in PEG, so repeating an expression that matches the empty string should similarly be made an error.

**Comment by kevinmehall** [comment]
Also, I meant to find a new syntax for inverted character sets that would be compatible with token trees and the new expansion into `match` arms, but since the hack with negative lookahead worked, I never came up with a replacement. It is a common enough pattern that it probably deserves its own syntax, though.

For now, I added an example inverted character set to the upgrade steps in the [0.6 release notes](https://github.com/kevinmehall/rust-peg/releases/tag/0.6.0) that hopefully helps clarify this for others.

**Comment by hfiguiere** [comment]
Thanks !

**Comment by kw217** [comment]
Hi - I'm using `0.6.2` and I don't believe this is completely fixed. Here is my code, which leads to an infinite loop:

```rust
use peg;

pub fn main() {
    test_parser::top("test").unwrap()
}

peg::parser!{
    grammar test_parser() for str {
        rule _() = " "*
        rule nl() = _* "\n" _*
        pub rule top() = nl()
    }
}
```

It would be nice if this was spotted by the compiler.

It was quite hard to find this in my (larger) codebase; is there a way to set a maximum recursion depth or parse time or something, to aid debugging?

**Comment by kevinmehall** [comment]
Yeah, this issue is still open. As of 0.6, `rust-peg` checks for infinite loops by left recursion, but it does not yet check for `*` infinitely matching zero characters.

Your best bet for debugging issues like this would be the [`trace` feature](https://docs.rs/peg/0.6.2/peg/#tracing). Or a backtrace in a debugger like GDB should give you a reasonable stack trace of `parse_<rulename>` calls.

**Comment by kw217** [comment]
OK, thanks.

**Comment by kw217** [comment]
Great, thanks!
