### ISSUE TITLE
How to match string literals case insensitively

### ISSUE THREAD

**Issue by azul** [kevinmehall/rust-peg#216]
I'm working on upgrading a codebase from peg 0.5 to 0.6.

There's a bunch of rules like this one in there:
```
pub cmd_help -> SmtpCommand
        = "help"i s:strparam* NL
        { SmtpCommand::Help(s) }
```

In 0.6 the `i` modifier of `"help"i` no longer works. What's the recommended way to do this now?

**Comment by kevinmehall** [comment]
The `"str"i` syntax got removed because as a procedural macro, the syntax now has to conform to Rust's tokenization rules. Having it built-in also brought up issues of [what exactly "case-insensitive" means](https://github.com/kevinmehall/rust-peg/issues/64) in the context of Unicode.

However, the addition of rule arguments allows you to define your own rule that matches a given literal string. Something like:

```
rule i(literal: &'static str) = input:$([_]*<{literal.len()}>) {? if input.eq_ignore_ascii_case(literal) { Ok(()) } else { Err(literal) } }
    
pub rule cmd_help() -> SmtpCommand = i("help") s:strparam()* NL() { SmtpCommand::Help(s) }
```

Breaking that down, `[_]` accepts any single character, `[_]*<{literal.len()}>` accepts a string with the same length as the literal, `$()` gets the corresponding slice of the input string, and the `{? }` tests whether it is a case-insensitive match or returns the literal as the "Expected" error message. That should work for ASCII literals; would need some additional complexity to handle Unicode.

This is the kind of thing that I'd like to eventually get into a kind of "standard library" of common rules: https://github.com/kevinmehall/rust-peg/issues/201.

**Comment by kevinmehall** [comment]
Alternatively, if all the literals in your language are case insensitive, you could define the grammar for your own struct wrapping `str` or `&[u8]` and redefine `""` literals to behave however you want. Literals compile down to calls to [`ParseLiteral::parse_string_literal`](https://github.com/kevinmehall/rust-peg/blob/9d0f278dfc961f62221e666c215172a0e0caee35/peg-runtime/str.rs#L48-L57), which you could define for a custom input type in a way that uses case-insensitive string comparison instead of bytewise comparison.

**Comment by azul** [comment]
I still have to try this out. But looks like it's gonna work.
Will close this issue for now and reopen if i run into problems.

**Comment by azul** [comment]
Worked like a charm for me.
