### ISSUE TITLE
Switch to another rule on not matched string

### ISSUE THREAD

**Issue by no111u3** [kevinmehall/rust-peg#222]
For rules (where expr - some expression rule)
```rust
pub rule reg8() -> Reg8
            = r_name:$(['r' | 'R'] ['0'..='9']*<1,2>) { Reg8::from_str(r_name.to_lowercase().as_str()).unwrap() }

        pub rule reg16() -> Reg16
            = r_name:$(['x' | 'y' | 'z' | 'X' | 'Y' | 'Z']) { Reg16::from_str(r_name.to_lowercase().as_str()).unwrap() }

        pub rule index_ops() -> IndexOps
            = "-" r:reg16() { IndexOps::PreDecrement(r) }
            / r:reg16() "+" e:expr() { IndexOps::PostIncrementE(r, e) }
            / r:reg16() "+" { IndexOps::PostIncrement(r) }
            / r:reg16() { IndexOps::None(r) }


        pub rule instruction_ops() -> InstructionOps
            = ind:index_ops() { InstructionOps::Index(ind) }
            / r8:reg8() { InstructionOps::R8(r8) }
            / e:expr() { InstructionOps::E(e) }
```
And for test case such as:
```rust
assert_eq!(
            document::instruction_ops("zl"),
            Ok(InstructionOps::E(Expr::Ident("zl".to_string())))
        );
```

I want than string not match with previous rule it will be match to another rule, but in this case I have an error: 
```
Expected :Ok(E(Ident("zl")))
Actual   :Err(ParseError { location: LineCol { line: 1, column: 2, offset: 1 }, expected: ExpectedSet { expected: {""+"", "EOF"} } })
```

IMO will be better switch to other case instead an error.

**Comment by kevinmehall** [comment]
Unlike regex, PEG backtracks and tries alternatives only when a rule fails, not after it succeeds. In this case, the `reg16` via the last line of `index_ops` matches the "z", `instruction_ops` succeeds, and then the parse fails because there is remaining input. If you want `expr` to match the `zl` input instead, reorder the ordered-choice `/` to try that rule first, or add lookahead expressions to disambiguate the grammar. For instance if the characters in `reg16` should not be matched at the beginning of a longer identifier, you could end that rule with `!(ident_char())` to fail the match by looking ahead at the next character. Alternatively, you could deal with this in a lexer and handle tokens instead of characters in the parser.
