### ISSUE TITLE
Getting position as (line, col) during parsing

### ISSUE THREAD

**Issue by bbqsrc** [kevinmehall/rust-peg#228]
I am aware of position!{} for getting the absolute 0-indexed position in the string, but how can one get it as a line and column?

**Comment by kevinmehall** [comment]
This is kind of beyond the scope of rust-peg. I'd recommend using byte offsets in the AST and then mapping to line-column for external use. You could use [codemap](https://github.com/kevinmehall/codemap) or implement your own similar data structure to pre-compute the positions of line starts and then binary search it to find line numbers.

`rust-peg` does contain a [very minimal implementation](https://github.com/kevinmehall/rust-peg/blob/8898f6445f2efeaf50142cd7355178a75bd3d559/peg-runtime/str.rs?ts=4#L25-L35) of the conversion for its default error reporting, but it would be highly inefficient to run for every AST node since it does a linear scan from the beginning every time.

**Comment by D4Delta** [comment]
I know this is closed, just letting you know it would be really great to have this feature

I'm coming from OCaml's [Menhir](http://gallium.inria.fr/~fpottier/menhir/) and it has [positions](http://gallium.inria.fr/~fpottier/menhir/manual.html#sec50), I searched for a similar library in Rust and I found your library among others, but I like your syntax the most

Peg is awesome, it has everything I need, precedence level, associativity... but it's just missing this one feature, it's such a shame
I'll try using codemap, but I'm not sure how I'm going to do that considering I only have `position!()` which is relative to the last token

**Comment by kevinmehall** [comment]
The reason for this is that parser itself doesn't know or care what a line or column is. Lines depend on your definition of newline, and columns are even harder: count bytes vs codepoints vs graphemes, and how to count tabs. 

`position!()` is bytes relative to start of input, so if you have an array of the byte offsets of newlines in the file, you can binary-search the array for the `position!()` to find the line number, and then count the column offset from there. If you choose to do this within the grammar rather than afterward, look at grammar arguments for passing that data in, and you could wrap it up in a rule that returns the position in the format of your choice.

**Comment by D4Delta** [comment]
> The reason for this is that parser itself doesn't know or care what a line or column is. Lines depend on your definition of newline, and columns are even harder: count bytes vs codepoints vs graphemes, and how to count tabs.
> 
> `position!()` is bytes relative to start of input, so if you have an array of the byte offsets of newlines in the file, you can binary-search the array for the `position!()` to find the line number, and then count the column offset from there. If you choose to do this within the grammar rather than afterward, look at grammar arguments for passing that data in, and you could wrap it up in a rule that returns the position in the format of your choice.

Thanks, I don't know if you read my comment, but I figured it out 1 hours after, I felt stupid so I removed it
(I thought position! was relative to the first character matched by the rule)
