### ISSUE TITLE
Prefix Operators in precedence! macro.

### ISSUE THREAD

**Issue by RamiHg** [kevinmehall/rust-peg#230]
Hello,

I'm trying to build a simple C-like expression parser as a proof-of-concept. I'm running into an issue that I've drilled down to the handling of prefix operators in the precedence! constructs.

I'm not too familiar with how precedence climbing works, but it seems like the atom and prefix rules in precedence! are not respecting the precedence level.  Indeed, in peg-macros/translate.rs, it seems that only post-rules are associated with precedence levels.

Here is a minimal example (derived from `arithmetic_infix_ast.rs`) that shows the problem:

```rust
extern crate peg;

peg::parser!( grammar arithmetic() for str {
    rule _() = [' '|'\n'|'\t']*
    rule ident() -> &'input str = $(['a'..='z']+)

    rule mul_div_op() -> &'static str =
        "*"    { "*" }   /
        "/"    { "/" } /
        "%"    { "%" }

    rule unary_lhs() -> &'static str =
        "++"     {"++"} /
        "--"     {"--"} /
        "*"      {"*"} /
        "+"      {"+"} /
        "-"      {"-"};

    rule postfix_operator() -> &'static str =
        "++"   { "++" }/
        "--"   { "--" }

    pub rule expression() -> Box<InfixAst> = precedence!{
        x:(@) _ "+" _ y:@ { Box::new(InfixAst::BinOp("+", x, y))}
        x:(@) _ "-" _ y:@ { Box::new(InfixAst::BinOp("-", x, y)) }
        --
        x:(@) _  op:mul_div_op() _ y:@ { Box::new(InfixAst::BinOp(op, x, y)) }
        --
        op:unary_lhs() _ x:(@) { Box::new(InfixAst::UnaryPrefix(op, x)) }
        --
        x:(@) _ op:postfix_operator() {Box::new( InfixAst::UnaryPostfix(op, x)) }
        --
        i:ident() { Box::new(InfixAst::Ident(i.to_owned())) }
    }
});

#[derive(Debug, PartialEq, Eq, Clone)]
pub enum InfixAst {
    Ident(String),
    UnaryPrefix(&'static str, Box<InfixAst>),
    UnaryPostfix(&'static str, Box<InfixAst>),
    BinOp(&'static str, Box<InfixAst>, Box<InfixAst>),
}

fn main() {
    assert_eq!(
        arithmetic::expression("b-- * ++a / c").unwrap(),
        Box::new(InfixAst::BinOp(
            "/",
            Box::new(InfixAst::BinOp(
                "*",
                Box::new(InfixAst::UnaryPostfix(
                    "--",
                    Box::new(InfixAst::Ident("b".to_string()))
                )),
                Box::new(InfixAst::UnaryPrefix(
                    "++",
                    Box::new(InfixAst::Ident("a".to_string()))
                )),
            )),
            Box::new(InfixAst::Ident("c".to_string()))
        ))
    )
}
```

Output:

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `BinOp("-", Ident("b"), BinOp("/", UnaryPrefix("-", UnaryPrefix("*", UnaryPrefix("++", Ident("a")))), Ident("c")))`,
 right: `BinOp("/", BinOp("*", UnaryPostfix("--", Ident("b")), UnaryPrefix("++", Ident("a"))), Ident("c"))`'
```
The `b-- * ++a / c` expression is getting parsed as `b - (-(*++a) / c)`, since the unary prefix operators are getting bound more tightly than the postfix `--` operator.

Please let me know if I'm simply misunderstanding how precedence climbing works, and if combining infix and prefix/postfix operators is not really supported.

Cheers.

**Comment by kevinmehall** [comment]
Prefix operators do respect the precedence levels in deciding how the expressions following the operator are parsed, e.g. `(-a)+b` vs `-(a+b)`. What's going on here is slightly different, related to a different form of ambiguity.

In your grammar, there is an ambiguity between infix "-" and postfix "--". After seeing "b", it tries and matches the infix "-" first, then goes looking for an expression for the RHS of the "-". This matches the prefix "-". Traditionally, precedence climbing is used with a lexer which would handle this by lexing "-" and "--" as distinct tokens. When combining it with lexerless PEG parsing, you have to explicitly resolve this ambiguity. One way to do so would be to make the infix "-" look ahead to check that the next character is not also a minus: `"-" !"-"`.

It's an arbitrary implementation choice that the operators in `precedence!{}` are tested in precedence order. It's still PEG, and effectively an ordered choice, but you can't reorder the arms to choose a different parse tree because that would also change the precedence levels. I think the simplicity of not having to specify precedence levels numerically makes up for the loss of expressiveness, and negative lookahead should be sufficient to choose the resolution of the the few ambiguities that come up here.

**Comment by RamiHg** [comment]
That perfectly explains it. I understand now. Thanks for the detailed response!
