### ISSUE TITLE
Mutable variables in rules

### ISSUE THREAD

**Issue by khionu** [kevinmehall/rust-peg#247]
I have to move the owned value here into a mutable variable so I can perform `Vec::dedup`
```rust
peg::parser!{
    grammar input() for str {
        use crate::types::Feature;

        rule feature() -> Feature
            = f:$("gitops" / "dev") {
                match f {
                    "gitops" => Feature::GitOps,
                    "dev" => Feature::Dev,
                    _ => unreachable!(),
                }
            }

        pub rule feature_set() -> Vec<Feature>
            = f:feature() ** "," { let mut f = f; f.dedup(); f }
    }
}
```

**Comment by kevinmehall** [comment]
The only place this could be specified is something like `mut f:feature()`, but I don't think that's a good place for it because it mixes Rust and PEG semantics.

In general it's best to keep the Rust code embedded in the grammar simple, and avoid large blocks and imperative-style code. I'd suggest defining a `fn deduped<T>(mut f: Vec<T>) -> Vec<T> { let mut f = f; f.dedup(); f }` that you can call from the parser.

**Comment by kevinmehall** [comment]
By the way, your `rule feature()` could be more simply defined as 

```
rule feature() -> Feature
    = "gitops" { Feature::GitOps }
    /  "dev" { Feature::Dev }
```

**Comment by khionu** [comment]
Oh wow, didn't know you could have multiple Rust blocks on a single rule, thanks!
