### ISSUE TITLE
A few questions that the documentation leaves unanswered

### ISSUE THREAD

**Issue by ethindp** [kevinmehall/rust-peg#271]
I'm considering trying to use this crate to parse ACPI machine language (AML). The AML grammar definition is fully specified [here](https://uefi.org/specs/ACPI/6.4/20_AML_Specification/AML_Specification.html), but its a byte stream, not a character stream. As such, it contains grammar rules specific to byte streams. This particular challenge has raised some unique questions:

## Parsing literal bytes, not characters

The AML grammar has definitions involving actual bytes that are not within the ASCII character set (some of them even are multiple bytes). Example:

```
    DualNamePath := DualNamePrefix NameSeg NameSeg
    DualNamePrefix := 0x2E
```

where `NameSeg` is defined as:

```
    LeadNameChar := ‘A’-‘Z’ | ‘_’
    DigitChar := ‘0’ - ‘9’
    NameChar := DigitChar | LeadNameChar
    RootChar := "'"
    ParentPrefixChar := ‘^’
    ‘A’-‘Z’ := 0x41 - 0x5A
    ‘_’ := 0x5F
    ‘0’-‘9’ := 0x30 - 0x39
    ‘' := 0x5C
    ‘^’ := 0x5E
    NameSeg :=
        <LeadNameChar NameChar NameChar NameChar>
        // Notice that NameSegs shorter than 4 characters are filled with trailing underscores (‘_’s).
```

Is there a proper way of handling bytes and not characters? I presume the literal syntax would work, but that feels kinda cumbersome.

## Grammar rules that can go nowhere

The AML grammar defines rules that contain nothing as a possible case. Example:

```
    ByteList := Nothing | <ByteData ByteList>
    ByteData := 0x00 - 0xFF
    WordData := ByteData[0:7] ByteData[8:15]
        // 0x0000-0xFFFF
    DWordData := WordData[0:15] WordData[16:31]
        // 0x00000000-0xFFFFFFFF
    QWordData := DWordData[0:31] DWordData[32:63]
        // 0x0000000000000000-0xFFFFFFFFFFFFFFFF
    AsciiCharList := Nothing | <AsciiChar AsciiCharList>
    AsciiChar := 0x01 - 0x7F
    NullChar := 0x00
```

In the above grammar segment, `ByteData` can be optional. Is there a way to specify, for example, that a byte constant, prefixed by a byte prefix (in this case, 0x0A) is optional, but that the prefix is required? This is required for the following grammar rules:

```
ComputationalData := ByteConst | WordConst | DWordConst | QWordConst | String | ConstObj | RevisionOp | DefBuffer
    DataObject := ComputationalData | DefPackage | DefVarPackage
    DataRefObject := DataObject | ObjectReference
    ByteConst := BytePrefix ByteData
    BytePrefix := 0x0A
    WordConst := WordPrefix WordData
    WordPrefix := 0x0B
    DWordConst := DWordPrefix DWordData
    DWordPrefix := 0x0C
    QWordConst := QWordPrefix QWordData
    QWordPrefix := 0x0E
    String := StringPrefix AsciiCharList NullChar
    StringPrefix := 0x0D
```

As an example, say I'm defining the rule for `ByteConst`. Can I do the following?

```rust
rule byteConst() -> Option<u8> =
    prefix:0x0A data:ByteData()? {
    // data may be empty, but we know we have a possible byte list
    if let Some(d) = data {
        // Use the bytes...
    }
}
```

The `?` in the above rule means that that particular part of the rule is optional. Do I have to designate the (entire) rule as optional, or can I designate portions? (I know that the `**` operator exists, but if `ByteList` is its own rule, that's where my confusion begins.)

**Comment by kevinmehall** [comment]
> Parsing literal bytes, not characters

You choose the input type when declaring the parser. Rust's `str` is required to be utf-8, but you can use a `[u8]` slice as input, and rust-peg comes with implementations of its parsing traits for slices:

```
peg::parser! {
    grammar foo() for [u8] {
        rule dual_name_prefix() = [0x2E]
        rule lead_name_char() = [b'A'..=b'Z' | b'_'] // note that the element type is now `u8` not `char` so you have to use `b'` literals.
    }
}
```

You'd call the parsing functions and pass `&[u8]` instead of `&str`.

> Grammar rules that can go nowhere

The only thing syntactically wrong with your example is the hex literal syntax -- you want `[0x0A]` to match a single specific byte. The inside of the `[]` is a Rust pattern (just like an arm of a `match` statement) that is tested against the next character/byte/token of input.

However, if `ByteData` is defined as `[0x00..=0xff]` (or `[n]` if you want to capture the byte value as a variable), it doesn't make much sense to make that optional, since it would always match since the range covers every byte.

It looks to me like they use the prefix bytes to signal which data type follows, so you want the `/` choice operator to allow the different options rather than `?`. For the `ByteList` and `AsciiCharList` note that they're defined recursively as a way to say that it is repeated, and so the best PEG translation would be the `*` operator.

This could be something like:

```
use super::ComputationalData; // an enum

rule byte_data() -> u8 = [b] { b }
rule word_data() -> u16 =  [b1] [b2] { b1 | b2<<8  }
rule ascii_char_list() -> Vec<u8> = s:$([0x01..]*) [0x00] { s.to_owned() }

rule byte_prefix() = [0x0A]
rule byte_const() -> ComputationalData = byte_prefix() b:byte_data() { ComputationalData::Byte(b) }

rule word_prefix() = [0x0B]
rule word_const() -> CompurationalData = word_prefix() w:word_data() { ComputationalData::Word(w) }

rule string_const() = [0x0D] s:ascii_char_list() { ComputationalData::String(s) } 

rule computational_data() -> ComputationalData
  = byte_const()
  / word_const()
  / string_const()
```

Or equivalently (just inlining the rules):

```
rule computational_data() -> ComputationalData
    = [0x0A] [b] { ComputationalData::Byte(b) }
    / [0x0B] [b1] [b2] { ComputationalData::Word(b1 | b2<<8)
    / [0x0D] s:$([0x01..]*) [0x00] { ComputationalData::String(s.to_owned()) }
```

> Do I have to designate the (entire) rule as optional, or can I designate portions?

The `?` (or `*`) applies to an expression, not the whole rule. You can use parentheses for grouping. e.g. `"a"? ("b" ['0'..='9'])?` matches `""`, `"a"`, `"ab1"` and `"b2"`.
