### ISSUE TITLE
#[cache_left_rec] not work in peg v0.7.0

### ISSUE THREAD

**Issue by Lucifier129** [kevinmehall/rust-peg#278]
When I attach #[cache_left_rec] in a left-recursion rule, I got an error like below.

![image](https://user-images.githubusercontent.com/6636455/143401972-1623982e-9615-4d38-9a75-8dc0f6068c8b.png)

**Comment by Lucifier129** [comment]
It seems like `cache_left_rec` is an unpublished feature that was not in `peg v0.7.0`, any plan or roadmap to ship this extremely useful feature?

**Comment by kevinmehall** [comment]
It was implemented after the release of 0.7.0. I haven't had a chance to finish a new release yet but will do so soon.

**Comment by zsol** [comment]
I just wanted to say a big thank you @kevinmehall for being supportive of new ideas and implementations like `cache_left_rec` (as well as #269 which I still haven't gotten around to :smile: ). Your work has helped me write a full Python 3.9 CST parser in https://github.com/Instagram/LibCST/pull/566 (feel free to shoot drive-by comments on it BTW), which will power new Python 3.10 syntax for all users of LibCST. If there's anything I can do to help with the maintenance burden of `rust-peg`, let me know! Can't wait to depend on a released version of `rust-peg` instead of `git` :)

**Comment by kevinmehall** [comment]
0.8.0 has been released with `#[cache_left_rec]` support. :tada:
