### ISSUE TITLE
feature request: a way to query the current line number during parsing

### ISSUE THREAD

**Issue by mcandre** [kevinmehall/rust-peg#342]
Usage for PEG: I am writing a linter for makefiles.

I can scan makefiles into an AST thanks to PEG. And I can then scan the AST for subtrees to emit linter warnings. However, I am unsure how to copy the line number information into the returned parse node.

Can we please introduce a PEG macro for querying the current line number? Similar to the macros for pattern matching.

Then, I will be able to enrich my AST nodes with this information, and emit more specific linter warnings. A linter is less useful without the line numbers, when linting large files.

_Note that peg already supports this, when emitting parse error messages. Even the column number is supported. I just want the same exact information exposed to rule declarations._

**Comment by kevinmehall** [comment]
Use `position!()`, which returns the current byte offset into the input string. It usually makes more sense to store these byte offsets in the AST and convert to line:col form only when needed for an error message for performance and storage reasons, but you could do that mapping within the parser if you really needed to.

The [implementation in peg used for the default error messages](https://github.com/kevinmehall/rust-peg/blob/f62301b9f723e27cdf9e4a80e9081a01739bf294/peg-runtime/str.rs#L36) just counts the `\n' in the slice before the position, in linear time, since it's called at most once. That would be slow to run for every AST node. In Signalspec, I [build an index](https://github.com/signalspec/signalspec/blob/b0dfd386f846a0e39ef5f5791841a4d7cba3c55d/src/syntax/span.rs#L90) of line start offsets, and binary search it to convert byte position to line in logarithmic time.

**Comment by mcandre** [comment]
Yes, the current implementation would be inefficient for multiple, successive calls.

Line numbers have been requested by other GitHub users before me. I rather enjoy PEG and would love to see this feature gain more support.

**Comment by kevinmehall** [comment]
You could build the index before parsing, pass it in as a grammar argument, and write a rule that wraps `position!()` to do the lookup in the index. Doing that doesn't belong in this library because most users would be better off deferring byte position to line mapping past the AST anyway.

**Comment by mcandre** [comment]
Hmm, food for thought.

Thank you for offering (several) workarounds. I admit feeling some anxiety about managing my first AST. I'll see what I can do.

**Comment by mcandre** [comment]
> You could build the index before parsing, pass it in as a grammar argument, and write a rule that wraps position!() to do the lookup in the index.

Alright, I think that's what I want to do.

Could you please direct me to a working example, such as a unit test? Then I can copy that in detail, into my peg application.
