### ISSUE TITLE
Improve error prompt information when there is insufficient input

### ISSUE THREAD

**Issue by A4-Tacks** [kevinmehall/rust-peg#376]
**error output**:

```rust
error: proc macro panicked
 --> src/main.rs:1:1
  |
1 | / peg::parser!(
2 | |     grammar parser() for str
3 | | );
  | |_^
  |
  = help: message: index out of bounds: the len is 6 but the index is 6
```

from source

https://github.com/kevinmehall/rust-peg/blob/ffcead2608ffba8ec37d3a3c8365ad2efc0849af/peg-macros/tokens.rs#L124-L126
https://github.com/kevinmehall/rust-peg/blob/ffcead2608ffba8ec37d3a3c8365ad2efc0849af/peg-runtime/error.rs#L128-L133

I tried to improve, but couldn't find a good way to obtain the Location of the input eof

**Comment by kevinmehall** [comment]
Fixed in https://github.com/kevinmehall/rust-peg/commit/d8889528df7b259a092485c9a1ed32d4411cef77.

I don't know of a way to get a span pointing at the closing `}` of the macro, and also want to handle the case of an empty `peg::parser()`, so the span is just the full `Span::call_site()`, but at least it's not a panic.

```
error: expected one of "::", "<", "{" at end of input
 --> tests/compile-fail/incomplete_grammar.rs:4:1
  |
4 | / peg::parser!(
5 | |     grammar parser() for str
6 | | );
  | |_^
  |
  = note: this error originates in the macro `peg::parser` (in Nightly builds, run with -Z macro-backtrace for more info)
```
