### ISSUE TITLE
Performance problems

### ISSUE THREAD

**Issue by jonas-schievink** [kevinmehall/rust-peg#49]
I wrote a parser to recognize a Lua-like language, and it seems that it runs very slowly: Parsing the function call `f(1,2,3,4,5,6,6,7,87,8,9,9,5,5,4)` takes a whole 280 ms (according to `cargo bench`, which takes over a minute to complete).

The grammar I used can be found [here](https://github.com/jonas-schievink/lea/blob/bcb8883b48cc6106675301fd3cd5ac0a3652a695/lea.rustpeg).

Can this be due to my expression rules using one rule per precedence level (there are currently 8 precedence levels) or is `rust-peg` more likely to be the culprit?

Thanks

**Comment by untitaker** [comment]
I found that rust-peg's performance inproves vastly with compiler optimizations enabled.

**Comment by kevinmehall** [comment]
There's barely been any optimization effort put into the library at this point. As @untitaker noted, make sure you're using rustc with `-O` or cargo with `--release`.

The biggest performance issue is the lack of memoization. Without that, you will get exponential behavior in those deeply nested rules, as it will parse each bare `atom` 256 times before returning from `expression` by backtracking and re-parsing all higher-precedence rules each time the operator is not found and it proceeds to the second argument of the `/` operator.

Operator precedence is a little tricky in PEG -- I'll also point out that your grammar isn't quite right. Since both the left and right sides of the operator require a higher-precedence subexpression, expressions like `1 + 2 + 3` will fail to parse.

A common PEG idiom which solves that problem and avoids backtracking is something like `l:expr_add rs:(op:binop_mul, r:expr_add {(op, r)})*`. That does make the match action a little more complicated, especially with multiple possible operators in one rule (`binop_mul`), or if you want the AST to be a binary tree instead of containing a Vec.

Since these types of rules are so common, I've thought a little about adding syntax that generates a [Shunting yard](https://en.wikipedia.org/wiki/Shunting-yard_algorithm) parser embedded in the PEG. Something like:

```
expression = atom @ {
  "*" { ExprMul(lhs, rhs) }
  "/" { ExprDiv(lhs, rhs} }
  "+" { ExprAdd(lhs, rhs) }
  "-" { ExprSub(lhs, rhs) }
}
```

**Comment by jonas-schievink** [comment]
Thanks for your help!
Optimization was enabled automatically by `cargo bench`. Since it seems that operator precedences are next to impossible to implement efficiently in PEG, I think I'll use an external expression parser and have the PEG parse atomic expressions and binary operators into a list.
