### ISSUE TITLE
Return types of expressions w/ repetition operators

### ISSUE THREAD

**Issue by mgushee** [kevinmehall/rust-peg#53]
There appears to be a problem with expressions in the forms `expr*` and `expr+`. For example:

    fn main() {
        println!("{:?}", parser::sqayz("'aaaaa'");
    }

    peg! parser(r#"
        #[pub]
        sqayz -> String
            // No, I didn't really expect this to compile - just experimenting
            = ['] content:[a]* [']  { content.to_string() }
    "#);

Attempting to compile the above produces this error:

    Compiling pegtest02 v0.0.1 (file:///home/m/scratch/pegtest02)
    <quote expansion>:89:85: 89:103 error: type `collections::vec::Vec<()>` does not implement any method in scope named `to_string`
    <quote expansion>:89                                                                   name_498,ctxt_0.name_70,ctxt_0()

Okay, so `content:[a]*` returns a Vec type, as stated in the documentation. But apparently the specific type is Vec<()>. Just to confirm, I tried this:

    peg! parser(r#"
        #[pub]
        sqayz -> Vec<()>
            = ['] content:[a]* [']  { content }
    "#);

This compiles, and running the resulting program produces:

    Ok([(), (), (), (), ()])

... which doesn't seem like a very useful result; it's certainly not what I want. Okay, here's another version:

     peg! parser(r#"
        #[pub]
        sqayz -> String
            = ['] content:ayz [']  { content.to_string() }

        ayz -> String
            = [a]+                       { match_str.to_string() }
    "#);

This compiles, and produces the desired output:

    Ok("aaaaa")

Okay, one more:

    peg! parser(r#"
        #[pub]
        sqayz -> Vec<String>
            = ['] content:ayz+ [']  { content }

        ayz -> String
            = [a]                   { match_str.to_string() }
    "#);

This compiles, but produces the output:

    Ok(["a", "a", "a", "a", "a"])

I am not sufficiently knowledgeable about PEG to make any statements about standards-compliance (and I gather PEG isn't exactly a standard anyway), but some of the above behavior is certainly counterintuitive. My comments are as follows:

*  The statement in the documentation: `expression+ - Match one or more repetitions of expression and return the results as a Vec` is clearly incomplete. My experiments show that `<character_class>+` and `<character_class>*` return `&str`, as do `<literal_string>+` and `<literal_string>*` while `<nonterminal>+` and `<nonterminal>*` return vectors as stated.

* It seems that `<identifier>:<terminal>` produces a `Vec<()>`. If that result is intentional, or if the types of expression that can be labeled are restricted, I think some explanation is needed.

Thanks!

**Comment by kevinmehall** [comment]
The return types you're seeing aren't actually due to the repetition operators but the things inside them. 
Character classes, literals, and concatenations without semantic actions all return (). Thus, repeating them results in a `Vec<()>`.

You found the right way to extract substrings, though: use `match_str`. If you wanted your third example in a single line, you could do:

``` 
peg! parser(r#"
    #[pub]
    sqayz -> String
        = ['] content:([a]+  { match_str.to_string() }) [']  { content }       
"#);
```

Some PEG implementations (e.g. PEG.js) make character classes and literals return the matched string.  The majority of parser rules are used only for parsing the structure of the code, rather than extracting strings that will be used.  Originally, rust-peg couldn't return slices and had to return `String`, so returning unnecessary results would result in a lot of unnecessary `String` allocations. Now that we can return `&'input str`, this is less of a performance issue, but would still result in the allocation of unused `Vec<&str>` buffers, whereas `Vec<()>` is just a counter. Performance aside, the implicit returns are rarely used in practice.

The rules that do extract values are often reusable rules like `identifier`, `stringLiteral`, `number`, etc, and typically care about the entire matched string rather than its individual characters (as in your 4th example), so the `match_str` slice of the input string is more desirable than manually concatenating together the characters (another allocation) from the repetition result vector.

Would "Match one or more repetitions of expression and return a Vec of the expression's return values" clarify the distinction between the rule's return value and the portion of the input string that was matched by that particular expression?
