### ISSUE TITLE
On a match, give user the match line number and column, along with the byte position

### ISSUE THREAD

**Issue by gsingh93** [kevinmehall/rust-peg#80]
It would be convenient to give the user line and column numbers as well as the byte position on a match. This is just a guess, but it might be as easy as calling `pos_to_line` here: https://github.com/kevinmehall/rust-peg/blob/de754eaf88a6625419e5eee2b15bf8fc8f3047ad/src/translate.rs#L566

If that's the case, I can go ahead and add this.

**Comment by kevinmehall** [comment]
The existing implementation of `pos_to_line` is a rather expensive iteration through the string, so it wouldn't be good to call it on every action. Do you have an application in mind where you'd want this information in every action, instead of cheaply storing the byte position and computing only the relevant line numbers later as needed?

I want to make it easy to associate source position information with the resulting AST, but a realistic program would probably want to handle this along the lines of `rustc`'s [CodeMap](https://github.com/rust-lang/rust/blob/master/src/libsyntax/codemap.rs). It stores integer offsets into a map of all source files and only looks up file/line/column when needed for an error message. The missing rust-peg feature for that is the ability to pass a state object into the parse call that is accessible in the actions. In this case, it would need to pass the codemap offset of the current file.

**Comment by gsingh93** [comment]
You have a point that it would be expensive. The reason I suggested adding this is I don't think the user should have to implement this type of conversion themselves, even if it isn't hard to do. The `pos_to_line` function requires the client to pass in the original input source, which is also somewhat inconvenient to the user, so publicly exposing that might not be a good solution either.

Using something like a CodeMap would definitely be a better solution for a production application, but many users won't need something so elaborate while prototyping or for non-production applications. It would be nice to have some convenient way of getting line/column numbers with no extra code on the users part.

I can't think of any efficient solutions to this problem, maybe this really is something that should be left up to the client code. I'll close this for now.
